### ISSUE TITLE
パスワードリセット機能のページ作成

### ISSUE THREAD

**Issue by KentoBF5587** [KentoBF5587/bookstore_visitor#31]
- [ ] letteropnerの導入
- [ ] パスワードリセット機能の作成

**Comment by KentoBF5587** [comment]
**実装したいもの・解決したいもの：**
Sorceryモジュールを利用したパスワードリセット機能を本番環境で実装

**質問内容：**
お疲れ様です。

現在、Sorceryモジュールを利用したパスワードリセット機能を設定しています。ローカル環境ではletter_opener_webを利用してパスワード申請メールが送られるところから、ユーザーによるパスワードの変更が出来るところまでの動作は確認できました。

次に本番環境でもパスワードが変更出来るように実装を進めようと考えていますが、以下の3つの点について疑問に思いました。

①パスワードリセットのリンクが添付させたメールのfrom欄を埋めるために、新しくアプリ運営用のアカウントを作るべきか。それとも個人で使っている既存のアカウントで十分か。

②アカウントを作るとしたら、フリーメールを利用すれば良いのか？（Gメールは既に使用中のため、Outlook辺りがいいのかなと現段階では考えております）

③あるいはメールを設定せず、”このメールには返信が出来ない”等のメッセージを添えて、架空のメールアドレスを添えるだけで十分か。

ポートフォリオ作成に関してはどのような流れで進めるかを、念の為実装を進める前に相談させていただきたいと考えました。

よろしくお願いいたします。

**実装する際に参考にした資料：**
[【Webメール5社を徹底比較】ビジネス利用に向いているのは？](https://www.maildealer.jp/column/tool/web-email139.php)

**Comment by kenchasonakai** [comment]
Gmailで新しくアカウントを作ると全部解決しそうな気がします

どのメールサービスを作るかは調べて出てくる記事が多いものや知り合いで使ってる人がいるものを使うのが無難かなと思います

**Comment by KentoBF5587** [comment]
ありがとうございます！

Gmailで新しいアカウントを作る方法で進めてみます！！
