### ISSUE TITLE
6/4 MVPリリース

### ISSUE THREAD

**Issue by KentoBF5587** [KentoBF5587/bookstore_visitor#55]
## 各種情報
サービス名　ほんやがたり
サービスURL　https://bookstore-visitor.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

-  [x] ユーザー登録機能

- [x] 書店登録・検索機能

- [x] ログイン（メールアドレスでの登録） 

- [x] 本屋レビュー機能

- [x] レスポンシブ対応

## READMEレビュー時から変更した機能

※チェックがついたものはREADMEのMVPリリース用の機能に書いていなかったもので且つ実装済み

- [x] Bootstrapの導入

- [x] rubocopの導入 

- [x] GoogleMapAPIの導入

- [x] フラッシュメッセージの設定

- [x] フォーム入力時エラー情報を個別表示

- [x] 本屋情報に紐づくタグを選べる機能

- [ ] ログイン機能（別のSNSアカウントと連携させることで登録できる機能）

- [ ]  プロフィール作成・編集機能

- [ ] 登録された本屋に対して、「おすすめの本屋」「行ってみたい本屋」という名前でブックマークする機能

- [ ] 「おすすめの本屋」に紐づけてそこで買った本屋を登録できる機能

- [ ] ユーザーのプロフィール欄に紐付けて、「おすすめの本屋（レビューした本屋）」「行ってみたい本屋」を表示

- [ ] 利用規約

### 画像1
[![Image from Gyazo](https://i.gyazo.com/e0acb21437896308aec6b3fa3b4ba571.png)](https://gyazo.com/e0acb21437896308aec6b3fa3b4ba571)

↑本屋を探すをクリックするとアプリに投稿された本屋さんの情報がログインなしで閲覧できます

---
### 画像2
[![Image from Gyazo](https://i.gyazo.com/72012409a7b6fe7e0ea6218767a8e92c.png)](https://gyazo.com/72012409a7b6fe7e0ea6218767a8e92c)

↑本屋の詳細画面です
（しおりのアイコンがありますが、こちらは未実装の「行きたい本屋」のための機能になる予定です）

---
### 画像3
[![Image from Gyazo](https://i.gyazo.com/bb57c66ca5cb5bdf6420e9f9d143f74e.png)](https://gyazo.com/bb57c66ca5cb5bdf6420e9f9d143f74e)
↑「おすすめ文を読む」をクリックするとレビューが読めます

---
### 画像4
[![Image from Gyazo](https://i.gyazo.com/22bc249ca8fe1ac8cc7615ee9a2716e3.png)](https://gyazo.com/22bc249ca8fe1ac8cc7615ee9a2716e3)
↑ログインすると書店を追加したり、レビューを書くことが出来ます

---
### 画像5
[![Image from Gyazo](https://i.gyazo.com/01991637965fcf1aa0d951c3ff9908d6.png)](https://gyazo.com/01991637965fcf1aa0d951c3ff9908d6)
↑本屋情報の編集画面
（データの作り間違いが想定されるため、本屋の情報を投稿した人にのみ削除が可能です）
（本屋情報に関しては今回あえて「誰でも編集できる」かたちを取りました）
（今後ユーザーが退会することになっても、本屋情報は削除されないようモデルに設定してあります）

---
### 画像6
[![Image from Gyazo](https://i.gyazo.com/ea99518d18411d4a4e6a3459ef8c6241.png)](https://gyazo.com/ea99518d18411d4a4e6a3459ef8c6241)
↑本屋のレビュー（おすすめ文）画面
（こちらは作成者にのみ編集ボタンと削除ボタンが現れます）

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
